#:kivy 2.0.0

MDScreen:

    MDBoxLayout:

        id: box
        orientation: 'horizontal'
        
        ScrollView:
            id: scroll
            size_hint_x: .75
            do_scroll_x: True
            scroll_x:1

            StackLayout:
                orientation: 'tb-rl'
                size_hint: None ,1
                width: self.minimum_width
                pos_hint: {'center_x': .5}
    
                StackLayout:
                    orientation: 'tb-rl'
                    size_hint: None, 1
                    width: scroll.width *.3
                    
                    MDLabel:
                        text: 'Date'
                        size_hint_y: None
                        height: 99
                                    
                    MDLabel:
                        text: 'hi'
                        size_hint_y: None
                        height: 125
                    
                    MDLabel:
                        text: 'hi'
                        size_hint_y: None
                        height: 125

                    MDLabel:
                        text: 'hi'
                        size_hint_y: None
                        height: 125

                StackLayout:
                    orientation: 'tb-rl'
                    size_hint: None, 1
                    width: scroll.width *.3
                

                    MDLabel:
                        text: 'Date'
                        size_hint_y: None
                        height: 99
                                    
                    MDLabel:
                        text: 'hi'
                        size_hint_y: None
                        height: 125
                    
                    MDLabel:
                        text: 'hi'
                        size_hint_y: None
                        height: 125

                    MDLabel:
                        text: 'hi'
                        size_hint_y: None
                        height: 125


                    